version: 2016.03.1.dev{build}

environment:
  P: "c:/projects/libs"
  RDBASE: "c:/projects/RDKit"
  PATH: "%RDBASE%/lib;%PATH%"
  BOOST_ROOT: c:/Libraries/boost
  BOOST_LIBRARYDIR: c:/Libraries/boost/lib64-msvc-12.0


# branches to build
branches:
  # whitelist
  only:
    - master
    - appveyor_tuning

# Operating system (build VM template)
#os: Windows Server 2012 R2
os: unstable

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\RDKit

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: c:\projects\RDKit\build\INSTALL.vcxproj      # path to Visual Studio solution or project
  parallel: true
  verbosity: quiet

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\RDKit
  - mkdir c:\projects\RDKit\build
  - cd c:\projects\RDKit\build
  - cmake -G "Visual Studio 12 Win64" -DCMAKE_INSTALL_PREFIX=%P% -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DRDK_BUILD_SWIG_WRAPPERS=OFF -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DRDK_BUILD_FREESASA_SUPPORT=ON ..

#test_script:
#  - cd c:\projects\RDKit\build
#  - ctest

# scripts to run after build
#after_build:
#  - cd %P%
#  - 7z a c:\projects\sqlite\sqlite.zip * -tzip
#  - cd c:\projects\sqlite

#artifacts:
#  - path: sqlite.zip
#    name: sqlite.zip

#deploy_script:
#  - cd c:\projects\sqlite
#  - curl -T sqlite.zip --user %ACCOUNT% https://webdav.yandex.ru/libs/sqlite.zip
